import { Geist, Geist_Mono } from 'next/font/google';
import { Toaster } from 'sonner';
import ConditionalHeader from '../components/layout/ConditionalHeader';
import StoreHeader from '../components/layout/StoreHeader';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ConditionalHeader storeHeader={<StoreHeader />}>
                {children}
                </ConditionalHeader>
                <Toaster position="top-center" richColors />
            </body>
        </html>
    );
}
